language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
services:
- docker
script:
  - >
    wget -O- bit.ly/ansibletest | env
    ANSIBLE_VERSIONS="1.4.4 1.9.2 2.1.0.0"
    DOCKER_IMAGES="centos:6 centos:7 debian:7 fedora:20 fedora:21 fedora:24
    ubuntu:12.04 ubuntu:16.04"
    sh -x

after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: Ik1yq73B4KNEJixrNRv45/W/HuFOlGkInlom7ffWR0tV64LItJ+ZsNxauCn2NylzP8ggwfjGYKEez5b8foLSZmLAAZUyKNDZl0024SVqwMTqbFo9vI35mhyUExhIhBvCY/qSTmIri+jWNPcALCApbP3hnuTfwLuBuIxXQMxj0x/TTwyr43odllo3+xiejV+6/GdgvPHlE3H8GR1dLYRG2zym7BnyGeFexH/CKv0xHMORwk9TjkV4Ky9wUIIy2nn/D32Z8zUzeWCoo/xNeenMdrZHwerEuCyWRz5sIymtyavJqMsEkfIzXWPRCKOgg1xp1V0Y6t8LBNaBwAqdE4oQkZaWTJBt6lW0uoPdmYzrJwRdqjzlPg5kSH9L9556+Q5JCTzrOg1HBOZR0oj+DOdJw9iJ5k3Vo3pyGCod24tSfPuQ8A9599ZMV7+n1GGdJtVsj27i5+FOMBHLXOJwcxn0BMMw5/GkiCvGLbNAlMNm9ZCW3oYPZL2p1JR3EJvVTXmtWSV44HSJiqzcg0pza9LIzO0fbmWL4HOhSDFJQwJgtR7SlMaUjv0a1HDBS2FI+xJxFCb0pKzBmwQSs9gSV5XrfV2Pfj4sfz9eyHklCCvPldmX0xuK94+hB5xeXZBJdWhdRJxINFiwBqlRZAxpmfpUfXECN2O00+n8bEX1FMpCzKU=
  email:
    recipients:
      secure: gvpcDxP2fM1/bVGii7zgkplvRmKLzkdUTtc3jWTigfFLx5X8y0K29dda8L6wCsqPI3h86CjQg+IRplcwNzDwFppKdS5kQZFuOMAdveIzxz+ITToa/xipPh9R/KXIYG22IWKYjGC/xEHIqMqjf44odGp13K+3HWHO8qLboxlhSxt/RV/YiF4ft5Lt2YLs5643RNWBsb9SYW3NzAUONer23TFekvJbEJDSqfGkYm1VOzeOZ4Aj7Oc8B3ZK+oQgYquXHZ5pTA04RHCoNzmILDifKOBWBoD79nTJ4hzE6b3jpNsaqj5g47zHJzQUC8l2ToimfE5fZgo07KQ9x8BG2W6zWlk0wsQQhPdqdIS36pjGyiluxGzF1o0uUunpWvkEMVycvCo/p7up3H6TEPmInn2x+4hB5BcwQl/dog57fiVeXt8KKtGA9Jw3qRwDtm92TiRVxdyBu9FTMRh5Kgz9yrtN/oDf81uwlTGqGeXgG5v+isrnMv80DJFVqTLEplElDHb/yX+cJBXO7YScK4Y8pU+ogsWLYaQ42CngmWv3PYmRzlIJJAitHK7aQBM1WvGwcE+D2SrGmIykcyqMvpDBspaJCk0jEtbZA2d0crwK1+gCQbbC6Thx7bKuYqu84XeVk17cnOM8UKWpFOFA5Zp5wmVKAT7zgjSYxI/HiXbDqdhAAnU=
